### ISSUE TITLE
Export Rubric Scores script hanging on assignment

### ISSUE THREAD

**Issue by JmohrUD** [UCBoulder/canvas-userscripts#12]
Hello!

I'm having trouble exporting _one_ of my assignment rubric scores. The "Export Rubric Scores Exporting scores, please wait..." window pops up and just sits there. I have not been able to resolve the problem or replicate it in other assignments.

Additional info:
1. I am able to export other assignments from my Canvas, so far only this one is giving me trouble.
2. The assignment title and rubric criterion titles contain only alphanumeric text - I had an issue with something similar before (quotes maybe?) that you so kindly and quickly fixed!
3. The assignment criterion _descriptions_ used to contain line breaks (not sure if that would matter) but removing them did not help.
4. This is an individual assignment. I am able to export other assignments that are individual or group-assignments.
5. This assignment uses a "write in comments / scores" style rubric. I am able to export other assignments that use either rubric style.

Reference images of assignment title, rubric, and hanging export box image.
<img width="308" alt="Screen Shot 2022-03-10 at 10 56 21 AM" src="https://user-images.githubusercontent.com/90915240/157700947-a13f322f-bf3f-40e9-823e-ecaa8acacdce.png">
<img width="312" alt="Screen Shot 2022-03-10 at 10 56 06 AM" src="https://user-images.githubusercontent.com/90915240/157700949-e22f2425-7a18-44c3-ac3c-86029459ec99.png">
<img width="1317" alt="Screen Shot 2022-03-10 at 10 55 39 AM" src="https://user-images.githubusercontent.com/90915240/157700950-0b2307ea-9de9-40b3-9ca3-19cf7d9fb083.png">

**Comment by jashbycu** [comment]
@JmohrUD will you try uninstalling this userscript and then re-install it by visiting this link? https://github.com/UCBoulder/canvas-userscripts/raw/12-export-rubric-scores-script-hanging-on-assignment/export_rubric_scores.user.js

Then please try again and let me know how it goes. I added better error messages and tried to handle some potential causes of your problem. Thanks!

**Comment by JmohrUD** [comment]
Okay, progress! I got this error message: "Uncaught TypeError: Cannot read properties of undefined (reading 'hide_points')"

**Comment by JmohrUD** [comment]
Okay, thanks for looking into it! I have returned my version to the main branch source.

**Comment by jashbycu** [comment]
Hi @JmohrUD. I have more information from Canvas about what I believe causes this issue. Apparently when you create a rubric from within the Assignments tool by clicking the + Rubric button, the rubric gets tied to the assignment in a special way. If you then try to swap this rubric out for a different one on that assignment, the rubric enters a limbo state where it is partially deleted and partially not-deleted. So then if you try to re-associate the rubric with the assignment, it will appear correctly on the website, but it won't appear within the API, and thus this userscript I wrote will not be able to read its data.

Canvas is working on a fix, but in the meantime, the workaround is to use the [Undelete feature](https://community.canvaslms.com/t5/Canvas-Admin-Blog/Undeleting-things-in-Canvas/ba-p/267116) to restore the affected rubric. I know it doesn't look deleted, but it is in a sense, and restoring it should allow the userscript to work again. Another tip is to always create a new rubric from within the Rubrics tool (on the course nav sidebar), and then you can associate it with the assignment. Rubrics created this way won't be affected by the bug.

Please let me know if "undeleting" the rubric resolves this for you!

**Comment by JmohrUD** [comment]
Okay, there were a few rubric-related items in the undelete for this assignment, so I'm just gonna document what I did in order:

- Undeleted the most recent (and only) RubricAssociation. That did not fix it.
- Undeleted the most recent (1 of 2) Rubric.  That fixed it!

So I'm not sure if it was the combo both or just the latter, but thanks!

This is unrelated, but are you aware of a canvas enhancement to pull out the rubric criteria comments (when the free-form comments are enabled)? We have some meta-analyses we want to do where we look at TA comments but it's tedious to go through them in speedgrader.

**Comment by jashbycu** [comment]
I'm sorry, but I don't know of an enhancement that does this. It could be added to this userscript, but I don't know when it could be done by me or someone at CU: we aren't prioritizing new development in this repo at this time, and this wouldn't be a super simple change (it would also need to maintain compatibility with the import_rubric_scores script). Feel free to open a separate issue if you'd like: that way at least we will have a record of the request. Sorry I can't give you a better answer!
